public class Calculator {
  /**
   * Returns the sum of two input arguments
   * @param a First number
   * @param b Second number
   * @return Sum of a and b
   */
  public static Decimal addNumbers(Decimal a, Decimal b) {
    return a + b;
  }

  /**
   * Returns the difference of two input arguments
   * @param a First number
   * @param b Second number
   * @return Difference of a and b (a - b)
   */
  public static Decimal subtractNumbers(Decimal a, Decimal b) {
    return a - b;
  }
}
